//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SdVersion } from './misc.models';
import { IFileModel } from './file.models';

export interface IHypernetModel
{
	id: number;
	name: string;
	about: string;
	sdVersion: SdVersion;
	versions: IHypernetVersionModel[];
}
export interface IHypernetVersionModel
{
	id: number;
	hypernetId: number;
	hypernet: IHypernetModel;
	file: IFileModel;
	version: string;
	about: string;
	sourceLink: string;
	knownNames: string[];
}
