//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SdVersion } from './misc.models';
import { IFileModel } from './file.models';

export interface IVaeModel
{
	id: number;
	name: string;
	about: string;
	sdVersion: SdVersion;
	versions: IVaeVersionModel[];
}
export interface IVaeVersionModel
{
	id: number;
	vaeId: number;
	vae: IVaeModel;
	file: IFileModel;
	version: string;
	about: string;
	sourceLink: string;
	knownNames: string[];
}
