//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IImageOwnerModel } from './misc.models';
import { IFileModel } from './misc.models';

export interface IAlbumModel
{
	shortToken: string;
	deletedAt: string|null;
	createdAt: string;
	name: string;
	description: string;
	owner: IImageOwnerModel;
	thumbImage: IFileModel;
	albumImages: IAlbumImageModel[];
}
export interface IAlbumImageModel
{
	imageId: number;
	image: any;
	gridId: number;
	grid: any;
}
