//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IImageOwnerModel } from './misc.models';
import { IFileModel } from './file.models';
import { IImageModel } from './misc.models';
import { IGridModel } from './grid.models';

export interface IAlbumModel
{
	shortToken: string;
	deletedAt: string|null;
	createdAt: string;
	name: string;
	description: string;
	owner: IImageOwnerModel;
	thumbImage: IFileModel;
}
export interface IAlbumImageModel
{
	imageId: number;
	image: IImageModel;
	gridId: number;
	grid: IGridModel;
}
export interface IGetAlbumRequest
{
	shortToken: string;
}
export interface IGetAlbumResponse
{
	album: IAlbumModel;
	imagesCount: number;
}
export interface IAddAlbumImagesRequest
{
	albumShortToken: string;
	images: string[];
}
export interface IAddAlbumImagesResponse
{
	addedImages: string[];
}
export interface ICreateAlbumRequest
{
	name: string;
	description: string;
}
export interface IDeleteAlbumRequest
{
	shortToken: string;
}
export interface IDeleteAlbumResponse
{
}
export interface IDeleteAlbumImagesRequest
{
	albumShortToken: string;
	images: string[];
}
export interface IDeleteAlbumImagesResponse
{
	deletedImages: string[];
}
export interface ISearchAlbumRequest
{
	searchText: string;
	owner: string;
	fields: SearchAlbumInFieldType[];
	orderByField: SearchAlbumOrderByFieldType;
	orderBy: SearchAlbumOrderByType;
	skip: number;
	take: number;
}
export interface IEditAlbumRequest
{
	shortToken: string;
	name: string;
	description: string;
}
export enum SearchAlbumInFieldType {
	Name = 0,
	Description = 1,
	User = 2
}
export enum SearchAlbumOrderByType {
	Asc = 0,
	Desc = 1
}
export enum SearchAlbumOrderByFieldType {
	UploadDate = 0,
	UserName = 1
}
