//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SdVersion } from './misc.models';
import { IFileModel } from './file.models';

export interface IEmbeddingModel
{
	id: number;
	name: string;
	about: string;
	trigger: string;
	sdVersion: SdVersion;
	versions: IEmbeddingVersionModel[];
}
export interface IEmbeddingVersionModel
{
	id: number;
	embeddingId: number;
	embedding: IEmbeddingModel;
	file: IFileModel;
	version: string;
	about: string;
	sourceLink: string;
	knownNames: string[];
}
