//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IImageOwnerModel } from './misc.models';
import { IFileModel } from './misc.models';
import { IDirectoryModel } from './misc.models';
import { IImageModel } from './misc.models';

export interface IGridModel
{
	id: number;
	shortUrl: string;
	shortToken: string;
	deletedAt: string|null;
	createdAt: string;
	name: string;
	description: string;
	owner: IImageOwnerModel;
	gridImages: IGridImageModel[];
	xTiles: number;
	yTiles: number;
	xValues: string[];
	yValues: string[];
	minLayer: number;
	maxLayer: number;
	thumbImage: IFileModel;
	layersDirectory: IDirectoryModel;
}
export interface IGridImageModel
{
	order: number;
	image: IImageModel;
}
export interface IUploadGridRequest
{
	albumShortToken: string;
	file: any;
	xTiles: number;
	yTiles: number;
	xValues: string[];
	yValues: string[];
}
export interface IUploadGridResponse
{
	uploaded: boolean;
	reason: string;
	grid: IGridModel;
}
