//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IEditImageModel } from './misc.models';
import { IImageModel } from './misc.models';

export interface IDeleteImageRequest
{
	shortToken: string;
	manageToken: string | null;
}
export interface IDeleteImageResponse
{
	success: boolean;
	reason: string;
}
export interface IEditImageRequest
{
	manageToken: string;
	image: IEditImageModel;
}
export interface IEditImageResponse
{
	image: IImageModel;
	success: boolean;
	reason: string;
}
export interface IGetImageRequest
{
	shortToken: string;
}
export interface IGetImageResponse
{
	image: IImageModel;
}
export interface ICheckManageTokenRequest
{
	shortToken: string;
	manageToken: string;
}
export interface ICheckManageTokenResponse
{
	shortToken: string;
	manageToken: string;
	isValid: boolean;
}
export interface ISearchImageRequest
{
	searchText: string;
	owner: string;
	album: string;
	fields: SearchImageInFieldType[];
	softwares: string[];
	alsoFromGrids: boolean;
	onlyFromRegisteredUsers: boolean;
	searchAsRegexp: boolean;
	orderByField: SearchImageOrderByFieldType;
	orderBy: SearchImageOrderByType;
	skip: number;
	take: number;
}
export enum SearchImageInFieldType {
	Prompt = 0,
	Name = 1,
	Description = 2,
	User = 3
}
export enum SearchImageOrderByFieldType {
	UploadDate = 0,
	UserName = 1
}
export enum SearchImageOrderByType {
	Asc = 0,
	Desc = 1
}
export abstract class SoftwareGeneratedTypes
{
	public static Unknown: string = `Unknown`;
	public static AutomaticWebUi: string = `AutomaticWebUi`;
	public static DreamStudio: string = `DreamStudio`;
	public static NovelAi: string = `NovelAi`;
}
