//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IEditImageModel } from './misc.models';
import { IImageModel } from './misc.models';

export interface IDeleteImageRequest
{
	shortToken: string;
	manageToken: string;
}
export interface IDeleteImageResponse
{
	success: boolean;
	reason: string;
}
export interface IEditImageRequest
{
	manageToken: string;
	image: IEditImageModel;
}
export interface IEditImageResponse
{
	image: IImageModel;
	success: boolean;
	reason: string;
}
export interface IGetImageRequest
{
	shortToken: string;
}
export interface IGetImageResponse
{
	image: IImageModel;
}
export interface ICanEditRequest
{
	shortToken: string;
}
export interface ICanEditResponse
{
	shortToken: string;
	canEdit: boolean;
	manageTokenRequired: boolean;
}
export interface ICheckManageTokenRequest
{
	shortToken: string;
	manageToken: string;
}
export interface ICheckManageTokenResponse
{
	shortToken: string;
	manageToken: string;
	isValid: boolean;
}
