//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IEditImageModel
{
	shortToken: string;
	name?: string;
	description?: string;
}
export interface IImageParsedMetadataModel
{
	width: number;
	height: number;
	tags: IImageParsedMetadataTagModel[];
}
export interface IImageParsedMetadataTagModel
{
	software: string;
	source: string;
	name: string;
	value: string;
}
export interface IImageModel
{
	owner: IImageOwnerModel;
	originalImage: IFileModel;
	compressedImage: IFileModel;
	thumbImage: IFileModel;
	shortUrl: string;
	shortToken: string;
	deletedAt: string|null;
	createdAt: string;
	name: string;
	description: string;
	parsedMetadata: IImageParsedMetadataModel;
}
export interface IImageOwnerModel
{
	guid: string;
	login: string;
	isAnonymous: boolean;
}
export interface IUploadedFileModel
{
	uploaded: boolean;
	reason: string;
	manageToken: string;
	image: IImageModel;
}
export interface IUserModel
{
	guid: string;
	login: string;
	loginNormalized: string;
	createdAt: string;
	roles: string[];
	about: string;
}
export interface IFileModel
{
	id: number;
	name: string;
	directUrl: string;
	hash: string;
	mimeType: string;
	extension: string;
	size: number;
	createdAt: string;
}
export interface IServerErrorResponse
{
	statusCode: number;
	title: string;
	message: string;
	guid: string|null;
	moreData: string;
	innerException: string;
	modelState: { [key:string]: string[] };
}
export enum AudienceType {
	Unknown = 0,
	SdHub = 1
}
export enum CaptchaType {
	ReCaptchaV2 = 0
}
