//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { SdVersion } from './misc.models';
import { IGenerationSampleModel } from './gensample.models';
import { IFileModel } from './file.models';

export interface IModelModel
{
	id: number;
	name: string;
	about: string;
	sdVersion: SdVersion;
	versions: IModelVersionModel[];
}
export interface IModelVersionModel
{
	id: number;
	modelId: number;
	version: string;
	about: string;
	knownNames: string[];
	samples: IGenerationSampleModel[];
	files: IModelVersionFileModel[];
}
export interface IModelVersionFileModel
{
	modelVersionId: number;
	file: IFileModel;
	type: number;
	modelHashV1: string;
}
export interface ISearchModelRequest
{
	searchText: string;
	fields: SearchModelInFieldType[];
	sdVersions: SdVersion[];
	skip: number;
	take: number;
}
export interface IGetModelRequest
{
	id: number;
}
export interface ICreateModelRequest
{
	name: string;
}
export interface IEditModelRequest
{
	id: number;
	name: string;
	about: string;
	sdVersion: SdVersion;
}
export interface IDeleteModelRequest
{
	id: number;
}
export interface IDeleteModelResponse
{
}
export interface IEditModelVersionRequest
{
	modelId: number;
	versionId: number;
	version: string;
	about: string;
	knownNames: string[];
	files: { [key:string]: number };
}
export interface IDeleteModelVersionRequest
{
	modelId: number;
	versionId: number;
}
export enum SearchModelInFieldType {
	Name = 0,
	FullHash = 1,
	V1Hash = 2,
	KnownNames = 3
}
export interface IAddModelVersionRequest
{
	modelId: number;
}
