//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IUploadedFileModel } from './misc.models';

export interface IUploadRequest
{
	files: any[];
}
export interface IUploadResponse
{
	files: IUploadedFileModel[];
}
