name: build-container
on:
  push:
    branches:
      - master
      - ci
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set lower case owner name
        run: |
          echo "REGISTRY=ghcr.io"                >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${REPO,,}"            >> ${GITHUB_ENV}
          echo "IMAGE_TAG=${SHA,,}"              >> ${GITHUB_ENV}
          echo "CI_COMMIT_REF_NAME=${REF_NAME}"  >> ${GITHUB_ENV}
          echo "CI_COMMIT_SHA=${SHA}"            >> ${GITHUB_ENV}
          echo "DOCKER_BUILDKIT=1"               >> ${GITHUB_ENV}

        env:
          REPO: "${{ github.repository }}"
          SHA: "${{ github.sha }}"
          REF_NAME: "${{ github.ref_name }}"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Config
        run: docker-compose --env-file ./dc/env-build config

      - name: Build
        run: docker-compose --env-file ./dc/env-build build

      - name: Push
        run: docker-compose --env-file ./dc/env-build push
