name: build-container
on:
  push:
    branches:
      - master
      - ci
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.head_ref }}
  CI_COMMIT_REF_NAME: ${{ github.head_ref }}
  CI_COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker-compose --env-file ./dc/env-build build

      - name: Push
        run: docker-compose --env-file ./dc/env-build push
